### ISSUE TITLE
UniversalEnemies

### ISSUE THREAD

**Issue by DarkiBoi** [minecraft-initiative/UniversalFriends#26]
Same thing but with enemies. I think this needs no further explanation

**Comment by zeroeightysix** [comment]
The name might be a bit misleading, but, yes, this library features enemies and neutrals as well.

**Comment by 5HT2** [comment]
Look at the code ^^
The way I think it works atm is you have enemy and friend, and you can assign a number and their username and so on.

**Comment by nothub** [comment]
For reference, check the [standard](https://github.com/minecraft-initiative/UniversalFriends/blob/master/STANDARD.md).
