### ISSUE TITLE
license needed

### ISSUE THREAD

**Issue by nothub** [minecraft-initiative/UniversalFriends#4]
so other projects can use it without fear of it being licensed under smthg they cant use.

**Comment by IronException** [comment]
true. you have a license suggestion?

**Comment by 5HT2** [comment]
LGPLv3

library, GPL

**Comment by nothub** [comment]
with lgpl, you wont be able to use gpl licensed code in this project, but every gpl project gonna be able to use the license in their project. if this is not an option use gpl which allows both ways.

**Comment by 5HT2** [comment]
Why would somebody use GPL code in this? This is meant to be a library, no?

**Comment by nothub** [comment]
idk, i dont have a time machine :P

**Comment by nothub** [comment]
for a simple readup, check: https://choosealicense.com/

**Comment by 5HT2** [comment]
true. changing license requires agreement from all contributors so if it's soon in the future it wouldn't be a problem. 

And if you mean using a library that's GPL, you can do that. You can't do straight GPL code though.

**Comment by 5HT2** [comment]
Modified MIT is always an option

https://tldrlegal.com/license/gnu-lesser-general-public-license-v3-(lgpl-3)

https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)

https://tldrlegal.com/license/mit-license

**Comment by zeroeightysix** [comment]
Closed in #16
