### ISSUE TITLE
Setup actions

### ISSUE THREAD

**Issue by 5HT2** [minecraft-initiative/UniversalFriends#6]
waiting for #5

**Comment by zeroeightysix** [comment]
Opt for github actions instead.

**Comment by 5HT2** [comment]
Does that have the same badges for builds failed / successful?

**Comment by zeroeightysix** [comment]
> Does that have the same badges for builds failed / successful?

It might, I don't know.
I think having your builds here, on GitHub, instead of through an external service is much more important though.

**Comment by 5HT2** [comment]
That's a good point

**Comment by zeroeightysix** [comment]
Closed in 898836b677eda576ed4b9cb1c524dc927086ecd9
