### ISSUE TITLE
operations

### ISSUE THREAD

**Issue by IronException** [minecraft-initiative/UniversalFriends#8]
basically that you can shift the value of every player. For example half it. This is meant to be able to make room if you tend to give the similar values to players.

**Comment by zeroeightysix** [comment]
Suppose we implement a helper class to perform these kinds of operations for you:
`ConfigurationOperations.halve(myConfiguration)`

Should this produce a **new** `Configuration`, or mutate the provided `Configuration`?

**Comment by IronException** [comment]
To make room between values it wouldn't make sense to have these new values only in the new class. So I think it should be an actual change. Although you can probably break things with that...

**Comment by IronException** [comment]
Also, I think it would be useful to have operations that behave like functions. so you can half values that are above 1 so they come closer to 1

for instance halveBetween(1, 2) does (value - 1) / 2

**Comment by zeroeightysix** [comment]
> To make room between values it wouldn't make sense to have these new values only in the new class. So I think it should be an actual change. Although you can probably break things with that...

Mutating people's objects isn't always the best (idiomatic) choice though. Look at languages like rust or kotlin - where some features are designed to make you write more immutable code.

I can't think of a good example to explain why though.

**Comment by IronException** [comment]
I agree that these things should be immutable. But when you as a user decide to dislike everyone you have met. You would have to decrease the friendship value for each player individually. We might talk about 2 different things here but I thought these operations were to help with that. To make it possible for the user to change everybody's value easier.

What would you use the operations for?

**Comment by zeroeightysix** [comment]
> I agree that these things should be immutable. But when you as a user decide to dislike everyone you have met. You would have to decrease the friendship value for each player individually. We might talk about 2 different things here but I thought these operations were to help with that. To make it possible for the user to change everybody's value easier.
> 
> What would you use the operations for?

I'm talking about exactly how the library would treat configuration objects operations are being performed on.

Let's say we have a configuration, of which we want to halve all the friendliness values of:
```java
Configuration<Person> peopleConfiguration;
```
If operations were to mutate the configuration:
```java
Configurations.halveFriendlinessValues(peopleConfiguration);
// peopleConfigurations has now been mutated
// We don't know what the original configuration looked like.
```
If Configurations were to create a copy and mutate that copy:
```java
Configuration<IPerson> mutatedCopy = Configurations.halveFriendlinessValues(peopleConfiguration);
// peopleConfiguration remains unchanged, and we receive a new Configuration from the operation, which is a copy of the provided configuration, with the operation applied.
// Because we create a deep copy, our generic type dissapears and becomes just IPerson.
// While more idiomatic, deep copies are harder to do correctly and might mean we lose some information along the way.
```

**Comment by zeroeightysix** [comment]
Personally, I'd opt for mutating the `Configuration` because it's more predictable, doesn't introduce a loss of types and simpler to implement.
